
version: '2.1'
services:
  image:
    extends:
      file: docker-compose-base.yml
      service: base-zipkin
    container_name: ${CONTAINER_HOST_NAME:-zipkin}
    hostname: ${CONTAINER_HOST_NAME:-zipkin}
    environment:
      - STORAGE_TYPE=${STORAGE_TYPE:-elasticsearch}
      - ES_HOSTS=${ES_HOSTS:-http://192.168.3.40:9200}
    ports:
    - "${SERVER_PORT:-9411}:9411"
    restart: always
    volumes:
    - data:/data

networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      #- subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
